// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI5yevneOsSZeDj9crIxvMHCMxVa-_C2I',
    appId: '1:524217360295:web:dc7e23301ba6ec591ea082',
    messagingSenderId: '524217360295',
    projectId: 'nossas-lembrancas-d46a2',
    authDomain: 'nossas-lembrancas-d46a2.firebaseapp.com',
    storageBucket: 'nossas-lembrancas-d46a2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPiERrDmDIHFFarvoc4rLB1I9DQf6d7jU',
    appId: '1:524217360295:android:422a48938eefc8001ea082',
    messagingSenderId: '524217360295',
    projectId: 'nossas-lembrancas-d46a2',
    storageBucket: 'nossas-lembrancas-d46a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHb8phGlMXAicFcpWnSLotcVXCQbCKzy0',
    appId: '1:524217360295:ios:bfdb946d10f455a81ea082',
    messagingSenderId: '524217360295',
    projectId: 'nossas-lembrancas-d46a2',
    storageBucket: 'nossas-lembrancas-d46a2.firebasestorage.app',
    iosBundleId: 'com.example.nossasLembrancas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHb8phGlMXAicFcpWnSLotcVXCQbCKzy0',
    appId: '1:524217360295:ios:bfdb946d10f455a81ea082',
    messagingSenderId: '524217360295',
    projectId: 'nossas-lembrancas-d46a2',
    storageBucket: 'nossas-lembrancas-d46a2.firebasestorage.app',
    iosBundleId: 'com.example.nossasLembrancas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI5yevneOsSZeDj9crIxvMHCMxVa-_C2I',
    appId: '1:524217360295:web:b67d3ea31cae76cb1ea082',
    messagingSenderId: '524217360295',
    projectId: 'nossas-lembrancas-d46a2',
    authDomain: 'nossas-lembrancas-d46a2.firebaseapp.com',
    storageBucket: 'nossas-lembrancas-d46a2.firebasestorage.app',
  );
}
